name: PHPStan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    name: Static Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --error-format=github
